TERM: screen-256color

font:
  size: 13.0
  normal:
    family: FiraCode Nerd Font
    style: Regular

  Bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: jetbrains-mono Nerd Font
    style: Italic

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  decorations: none

  dynamic_title: true

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 1

  padding:
    x: 10
    y: 10

  dynamic_padding: true

startup_mode: windowed

key: return,
mods: Command,
action: SpawnNewInstance

cursor:
  style: Block

use_thin_strokes: true

live_config_reload: true

# BEGIN ACE
colors:
  primary:
    background: '0x282828'
    foreground: '0xb3baba'
  cursor:
    text:       '0x282828'
    cursor:     '0xb3baba'
  normal:
    black:      '0x282828'
    red:        '0x3D6446'
    green:      '0x4C4F4F'
    yellow:     '0x616561'
    blue:       '0x8C6D66'
    magenta:    '0x6F8A67'
    cyan:       '0x888D78'
    white:      '0xb3baba'
  bright:
    black:      '0x7d8282'
    red:        '0x3D6446'
    green:      '0x4C4F4F'
    yellow:     '0x616561'
    blue:       '0x8C6D66'
    magenta:    '0x6F8A67'
    cyan:       '0x888D78'
    white:      '0xb3baba'

# END ACE